repos:
  - repo: local
    hooks:
      - id: ruff
        name: ruff-check
        description: "Run 'ruff' for extremely fast Python linting"
        language: system
        entry: ruff check --force-exclude
        types_or: [python, pyi]
        #args: []
        #require_serial: true
        #additional_dependencies: []
      
      - id: ruff-format
        name: ruff-format
        description: "Run 'ruff format' for extremely fast Python formatting"
        language: system
        entry: ruff format --force-exclude
        types_or: [python, pyi]
        #args: []
        #require_serial: true
        #additional_dependencies: []
      
      - id: mypy
        name: mypy
        description: "Run mypy"
        language: system
        entry: mypy
        types_or: [python, pyi]
        #args: []
        #pass_filenames: true
        #require_serial: true
        #additional_dependencies: []
        #minimum_pre_commit_version: '2.9.2'

      - id: quality
        name: quality
        description: "Run quality checks"
        language: system
        entry: support/quality.py
        types_or: [python]
        pass_filenames: true
