fail_fast: true


repos:
  - repo: local
    hooks:
      - id: ruff-format
        name: ruff-format
        description: "Run 'ruff format' for extremely fast Python formatting"
        language: system
        entry: ruff format --force-exclude --exit-non-zero-on-format
        types_or: [python, pyi]

      - id: ruff
        name: ruff-check
        description: "Run 'ruff' for extremely fast Python linting"
        language: system
        entry: ruff check --force-exclude --fix --exit-non-zero-on-fix
        types_or: [python, pyi]
      
      - id: mypy
        name: mypy
        description: "Run mypy"
        language: system
        entry: mypy
        types_or: [python, pyi]

#      - id: quality
#        name: quality
#        description: "Run quality checks"
#        language: system
#        entry: support/quality.py
#        types_or: [python]
#        pass_filenames: true
#        args: ["-v"] 
